services:
  postgres:
    image: postgres:16
    container_name: empay_postgres
    restart: always
    environment:
      POSTGRES_USER: empay_user
      POSTGRES_PASSWORD: empay_pass
      POSTGRES_DB: empay_db
    ports:
      - "5432:5432"
    volumes:
      - empay_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: empay_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@empay.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  empay_pgdata:
