"""init

Revision ID: c57fabc01824
Revises: 
Create Date: 2026-05-02 12:46:27.069840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c57fabc01824'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'EMPLOYEE', 'HR_OFFICER', 'PAYROLL_OFFICER', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('employees',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('designation', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('employee_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('manager_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code')
    )
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=True)
    op.create_table('leave_types',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('max_days', sa.Integer(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payruns',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'PROCESSED', name='payrunstatus'), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('employee_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('working_hours', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'HALF_DAY', 'ON_LEAVE', name='attendancestatus'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_date'), 'attendance', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_employee_id'), 'attendance', ['employee_id'], unique=False)
    op.create_table('leave_allocations',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('employee_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('leave_type_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('used_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_allocations_employee_id'), 'leave_allocations', ['employee_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('employee_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('leave_type_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='leavestatus'), nullable=False),
    sa.Column('reviewed_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False)
    op.create_table('payslips',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('payrun_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('employee_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('basic', sa.Float(), nullable=False),
    sa.Column('hra', sa.Float(), nullable=False),
    sa.Column('other_allowances', sa.Float(), nullable=False),
    sa.Column('gross', sa.Float(), nullable=False),
    sa.Column('pf_deduction', sa.Float(), nullable=False),
    sa.Column('prof_tax', sa.Float(), nullable=False),
    sa.Column('leave_deduction', sa.Float(), nullable=False),
    sa.Column('net_pay', sa.Float(), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=False),
    sa.Column('days_present', sa.Integer(), nullable=False),
    sa.Column('days_on_leave', sa.Integer(), nullable=False),
    sa.Column('unpaid_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payrun_id'], ['payruns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslips_employee_id'), 'payslips', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payslips_payrun_id'), 'payslips', ['payrun_id'], unique=False)
    op.create_table('salary_config',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('employee_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('basic', sa.Float(), nullable=False),
    sa.Column('hra', sa.Float(), nullable=False),
    sa.Column('other_allowances', sa.Float(), nullable=False),
    sa.Column('pf_rate', sa.Float(), nullable=False),
    sa.Column('professional_tax', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_config_employee_id'), 'salary_config', ['employee_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_config_employee_id'), table_name='salary_config')
    op.drop_table('salary_config')
    op.drop_index(op.f('ix_payslips_payrun_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_employee_id'), table_name='payslips')
    op.drop_table('payslips')
    op.drop_index(op.f('ix_leave_requests_employee_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_leave_allocations_employee_id'), table_name='leave_allocations')
    op.drop_table('leave_allocations')
    op.drop_index(op.f('ix_attendance_employee_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_date'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_table('payruns')
    op.drop_table('leave_types')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
